name: Build Geode Mod

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
